In [ ]:
import yfinance as yf
import pandas as pd

In [ ]:
#We do need by hand to define a Dictonary which has Company name and Ticker
#We can't download data without a ticker
#We could also just use an arrenge with tickers

In [ ]:
companies={"Apple": "AAPL", "Microsoft":"MSFT", "Nvidia":"NVDA", "Amazon":"AMZN"
}
tickers = ["AAPL", "MSFT", "NVDA", "AMZN"]
tickers = ["AAPL.US", "MSFT.US", "NVDA.US", "AMZN.US"]

In [19]:
#Try using Stooq
import pandas as pd
from datetime import datetime, timedelta

tickers = ["AAPL.US","MSFT.US"]
end=datetime.today()
start=end-timedelta(days=2*365)
flag=True
for ticker in tickers:
    url=f"https://stooq.com/q/d/l/?s={ticker}&d1={start:%Y%m%d}&d2={end:%Y%m%d}&i=d"
    df_temp=(pd.read_csv(url,parse_dates=["Date"])
        .set_index("Date")
        .sort_index())
    df_temp.columns = [f"{ticker} Open", f"{ticker} High", f"{ticker} Low", f"{ticker} Close", f"{ticker} Volume"]
    if flag:
        data=df_temp
        flag =False
    else:
        data=data.join(df_temp)

In [20]:
data

,AAPL.US Open,AAPL.US High,AAPL.US Low,AAPL.US Close,AAPL.US Volume,MSFT.US Open,MSFT.US High,MSFT.US Low,MSFT.US Close,MSFT.US Volume
Date,,,,,,,,,,
2024-03-07,167.782,169.349,167.126,167.633,72350481,403.852,407.4900,399.9930,406.854,1.882364e+07
2024-03-08,167.633,172.295,167.574,169.349,76889186,405.680,408.1270,402.0710,403.950,1.810333e+07
2024-03-11,171.541,172.970,170.658,171.353,60630058,401.506,403.4140,399.0180,402.261,1.621132e+07
2024-03-12,171.749,172.622,169.627,171.827,60313394,405.343,413.2490,404.5170,412.959,2.258317e+07
2024-03-13,171.373,171.782,169.379,169.744,52916866,415.764,415.8440,409.1510,412.782,1.721209e+07
...,...,...,...,...,...,...,...,...,...,...
2026-03-02,262.410,266.530,260.200,264.720,41827946,392.855,401.1900,390.6300,398.550,3.547491e+07
2026-03-03,263.480,265.560,260.130,263.690,38568921,393.140,406.7000,392.6700,403.790,3.819921e+07
2026-03-04,264.650,266.150,261.420,262.450,39803119,401.265,411.0326,400.3100,405.000,3.580799e+07
2026-03-05,260.790,261.555,257.250,260.250,49658626,404.420,411.6100,404.4000,410.680,3.900132e+07
2026-03-06,258.630,258.770,254.370,257.460,41120042,409.200,413.0500,408.5101,408.630,3.112386e+07

In [31]:
df=data

In [32]:
df.iloc[0][~df.iloc[0].notnull()]

Series([], Name: 2024-03-07 00:00:00, dtype: float64)

In [34]:
df.iloc[-1][~df.iloc[-1].notnull()]

Series([], Name: 2026-03-06 00:00:00, dtype: float64)

In [35]:
df

,AAPL.US Open,AAPL.US High,AAPL.US Low,AAPL.US Close,AAPL.US Volume,MSFT.US Open,MSFT.US High,MSFT.US Low,MSFT.US Close,MSFT.US Volume
Date,,,,,,,,,,
2024-03-07,167.782,169.349,167.126,167.633,72350481,403.852,407.4900,399.9930,406.854,1.882364e+07
2024-03-08,167.633,172.295,167.574,169.349,76889186,405.680,408.1270,402.0710,403.950,1.810333e+07
2024-03-11,171.541,172.970,170.658,171.353,60630058,401.506,403.4140,399.0180,402.261,1.621132e+07
2024-03-12,171.749,172.622,169.627,171.827,60313394,405.343,413.2490,404.5170,412.959,2.258317e+07
2024-03-13,171.373,171.782,169.379,169.744,52916866,415.764,415.8440,409.1510,412.782,1.721209e+07
...,...,...,...,...,...,...,...,...,...,...
2026-03-02,262.410,266.530,260.200,264.720,41827946,392.855,401.1900,390.6300,398.550,3.547491e+07
2026-03-03,263.480,265.560,260.130,263.690,38568921,393.140,406.7000,392.6700,403.790,3.819921e+07
2026-03-04,264.650,266.150,261.420,262.450,39803119,401.265,411.0326,400.3100,405.000,3.580799e+07
2026-03-05,260.790,261.555,257.250,260.250,49658626,404.420,411.6100,404.4000,410.680,3.900132e+07
2026-03-06,258.630,258.770,254.370,257.460,41120042,409.200,413.0500,408.5101,408.630,3.112386e+07

In [27]:
#start_date = '2015/01/01'
start_date=end-timedelta(days=2*365)

In [29]:
start_date

datetime.datetime(2024, 3, 7, 16, 20, 41, 90026)

In [28]:
f"bro {start_date:%Y%m%d}"

'bro 20240307'

In [41]:
period ="2M"
#rollig_std=df(["AAPL.US Open"]-df["AAPL.US Close"]).rolling(window="1Y").std()
pd.Timedelta("90D")

Timedelta('90 days 00:00:00')

In [ ]:
period="90D"
start = pd.to_datetime(start_date)
end = start + pd.Timedelta(period)
subset = df.loc[start:end]
desv=(subset["AAPL.US High"] - subset["AAPL.US Low"]).std()

In [44]:
desv

1.2189623432828474

In [48]:
desv=(df["AAPL.US High"] - df["AAPL.US Low"]).resample("2W").std()

In [55]:
aux=1/desv

In [80]:
len(desv)

53

In [82]:
len(aux)

53

In [93]:
end=datetime.today()
start=end-timedelta(days=2*365)
period_length = pd.Timedelta("2W")

def amount_of_periods(start, end, period_length):
    num_periods = (end - start) / period_length
    round_num_periods=(end - start)//period_length
    if num_periods!=round_num_periods:
        round_num_periods=round_num_periods+1
    return round_num_periods

In [57]:
desv

Date
2024-03-10    1.766353
2024-03-24    1.324719
2024-04-07    0.769973
2024-04-21    1.947890
2024-05-05    0.953334
2024-05-19    0.844000
2024-06-02    0.888680
2024-06-16    4.400940
2024-06-30    1.219116
2024-07-14    1.276482
2024-07-28    1.676204
2024-08-11    4.144637
2024-08-25    0.765741
2024-09-08    1.435477
2024-09-22    1.218513
2024-10-06    0.952745
2024-10-20    1.155770
2024-11-03    1.645974
2024-11-17    0.871184
2024-12-01    0.950125
2024-12-15    0.963424
2024-12-29    2.261346
2025-01-12    1.844557
2025-01-26    1.908217
2025-02-09    3.079686
2025-02-23    1.779144
2025-03-09    2.204804
2025-03-23    2.479785
2025-04-06    2.919048
2025-04-20    8.165193
2025-05-04    1.083386
2025-05-18    1.211373
2025-06-01    1.231815
2025-06-15    1.390282
2025-06-29    0.740024
2025-07-13    2.049593
2025-07-27    0.765732
2025-08-10    3.792201
2025-08-24    0.773633
2025-09-07    0.922726
2025-09-21    1.314632
2025-10-05    1.777118
2025-10-19    2.891037
2025-11-02    2.344109
2025-11-16    0.916210
2025-11-30    2.118231
2025-12-14    1.615978
2025-12-28    1.670174
2026-01-11    2.251137
2026-01-25    2.545157
2026-02-08    2.535552
2026-02-22    3.928718
2026-03-08    1.781432
Freq: 2W-SUN, dtype: float64

In [85]:
desv2=[aux,desv]

In [69]:
desv2=pd.concat(aux,desv)

TypeError: concat() takes 1 positional argument but 2 were given

In [75]:
desv2=[]
desv2.append(aux)
desv2.append(desv)

In [88]:
for i in range(len(desv2)):
    print("halo")

halo
halo

In [90]:
desv2[1]=1/desv2[1]

In [92]:
desv2[1].sum()

37.45110179477851

In [91]:
desv2[1]

Date
2024-03-10    0.566138
2024-03-24    0.754877
2024-04-07    1.298746
2024-04-21    0.513376
2024-05-05    1.048950
2024-05-19    1.184834
2024-06-02    1.125265
2024-06-16    0.227224
2024-06-30    0.820266
2024-07-14    0.783403
2024-07-28    0.596586
2024-08-11    0.241276
2024-08-25    1.305924
2024-09-08    0.696632
2024-09-22    0.820672
2024-10-06    1.049599
2024-10-20    0.865224
2024-11-03    0.607543
2024-11-17    1.147863
2024-12-01    1.052493
2024-12-15    1.037964
2024-12-29    0.442215
2025-01-12    0.542136
2025-01-26    0.524049
2025-02-09    0.324708
2025-02-23    0.562068
2025-03-09    0.453555
2025-03-23    0.403261
2025-04-06    0.342577
2025-04-20    0.122471
2025-05-04    0.923032
2025-05-18    0.825509
2025-06-01    0.811810
2025-06-15    0.719279
2025-06-29    1.351308
2025-07-13    0.487902
2025-07-27    1.305940
2025-08-10    0.263699
2025-08-24    1.292602
2025-09-07    1.083745
2025-09-21    0.760669
2025-10-05    0.562709
2025-10-19    0.345897
2025-11-02    0.426601
2025-11-16    1.091453
2025-11-30    0.472092
2025-12-14    0.618820
2025-12-28    0.598740
2026-01-11    0.444220
2026-01-25    0.392903
2026-02-08    0.394391
2026-02-22    0.254536
2026-03-08    0.561346
Freq: 2W-SUN, dtype: float64

In [76]:
desv2

[Date
 2024-03-10    0.566138
 2024-03-24    0.754877
 2024-04-07    1.298746
 2024-04-21    0.513376
 2024-05-05    1.048950
 2024-05-19    1.184834
 2024-06-02    1.125265
 2024-06-16    0.227224
 2024-06-30    0.820266
 2024-07-14    0.783403
 2024-07-28    0.596586
 2024-08-11    0.241276
 2024-08-25    1.305924
 2024-09-08    0.696632
 2024-09-22    0.820672
 2024-10-06    1.049599
 2024-10-20    0.865224
 2024-11-03    0.607543
 2024-11-17    1.147863
 2024-12-01    1.052493
 2024-12-15    1.037964
 2024-12-29    0.442215
 2025-01-12    0.542136
 2025-01-26    0.524049
 2025-02-09    0.324708
 2025-02-23    0.562068
 2025-03-09    0.453555
 2025-03-23    0.403261
 2025-04-06    0.342577
 2025-04-20    0.122471
 2025-05-04    0.923032
 2025-05-18    0.825509
 2025-06-01    0.811810
 2025-06-15    0.719279
 2025-06-29    1.351308
 2025-07-13    0.487902
 2025-07-27    1.305940
 2025-08-10    0.263699
 2025-08-24    1.292602
 2025-09-07    1.083745
 2025-09-21    0.760669
 2025-10-05    0.562709
 2025-10-19    0.345897
 2025-11-02    0.426601
 2025-11-16    1.091453
 2025-11-30    0.472092
 2025-12-14    0.618820
 2025-12-28    0.598740
 2026-01-11    0.444220
 2026-01-25    0.392903
 2026-02-08    0.394391
 2026-02-22    0.254536
 2026-03-08    0.561346
 Freq: 2W-SUN, dtype: float64,
 Date
 2024-03-10    1.766353
 2024-03-24    1.324719
 2024-04-07    0.769973
 2024-04-21    1.947890
 2024-05-05    0.953334
 2024-05-19    0.844000
 2024-06-02    0.888680
 2024-06-16    4.400940
 2024-06-30    1.219116
 2024-07-14    1.276482
 2024-07-28    1.676204
 2024-08-11    4.144637
 2024-08-25    0.765741
 2024-09-08    1.435477
 2024-09-22    1.218513
 2024-10-06    0.952745
 2024-10-20    1.155770
 2024-11-03    1.645974
 2024-11-17    0.871184
 2024-12-01    0.950125
 2024-12-15    0.963424
 2024-12-29    2.261346
 2025-01-12    1.844557
 2025-01-26    1.908217
 2025-02-09    3.079686
 2025-02-23    1.779144
 2025-03-09    2.204804
 2025-03-23    2.479785
 2025-04-06    2.919048
 2025-04-20    8.165193
 2025-05-04    1.083386
 2025-05-18    1.211373
 2025-06-01    1.231815
 2025-06-15    1.390282
 2025-06-29    0.740024
 2025-07-13    2.049593
 2025-07-27    0.765732
 2025-08-10    3.792201
 2025-08-24    0.773633
 2025-09-07    0.922726
 2025-09-21    1.314632
 2025-10-05    1.777118
 2025-10-19    2.891037
 2025-11-02    2.344109
 2025-11-16    0.916210
 2025-11-30    2.118231
 2025-12-14    1.615978
 2025-12-28    1.670174
 2026-01-11    2.251137
 2026-01-25    2.545157
 2026-02-08    2.535552
 2026-02-22    3.928718
 2026-03-08    1.781432
 Freq: 2W-SUN, dtype: float64]

In [77]:
type(desv2)

list

In [ ]:
start_date = '2015-01-01'
end_date = '2024-12-31'
# we could also request by period in an interval
#period=1, interval="1m"

#This if we want to save it in csv (I'm willing to change this to a MySQL thing)
for nombre, ticker in companies.items():
    try:
        print(f"Descargando datos de: {nombre} ({ticker})")
        data = yf.download(ticker, start=start_date, end=end_date)["Close"]
        #data= yf.download(tickers, period="1d", interval="1m")["Close"]
        if not data.empty:
            data.to_csv(f"{ticker}_{start_date}_to_{end_date}.csv")
        else:
            print(f"No se encontraron datos para {nombre} ({ticker})")
    except Exception as e:
        print(f"Error descargando {nombre} ({ticker}): {e}")

#This if we just want the close and nothing more
data = yf.download(tickers, period="1d", interval="1m")["Close"]

In [ ]:
#Revisar si https://github.com/ValueRaider/yfinance-cache es mejor alternativa
#o que más hay
#POlygon.io para tiempo real, parece la más sólida